### ISSUE TITLE
analyze_results output not matching expected, or even close

### ISSUE THREAD

**Issue by nullism** [jwnorman/aces-up#1]
Hi there,

I'm running your `main.py`, putting its output in `results.csv`, and running `analyze_results.py`. Out of 10,000 games, I see output like the following: 

```
Counter({13: 1906, 14: 1723, 15: 1442, 16: 1210, 17: 980, 18: 745, 19: 537, 20: 416, 21: 308, 22: 259, 23: 165, 24: 104, 25: 79, 26: 44, 27: 36, 28: 18, 29: 14, 31: 8, 30: 4, 35: 1, 36: 1})

{35: 0.0001, 36: 0.0001, 13: 0.1906, 14: 0.1723, 15: 0.1442, 16: 0.121, 17: 0.098, 18: 0.0745, 19: 0.0537, 20: 0.0416, 21: 0.0308, 22: 0.0259, 23: 0.0165, 24: 0.0104, 25: 0.0079, 26: 0.0044, 27: 0.0036, 28: 0.0018, 29: 0.0014, 30: 0.0004, 31: 0.0008}

{35: 10000.0, 36: 10000.0, 13: 5.25, 14: 5.8, 15: 6.93, 16: 8.26, 17: 10.2, 18: 13.42, 19: 18.62, 20: 24.04, 21: 32.47, 22: 38.61, 23: 60.61, 24: 96.15, 25: 126.58, 26: 227.27, 27: 277.78, 28: 555.56, 29: 714.29, 30: 2500.0, 31: 1250.0}
```
If I'm to understand your results correctly, the first row is "Cards Remaining: Number of times", correct? So, with a win-rate of 141:1, I should see "4: 70" or so, or at the very least, one win in 10,000 games. 

So, what's up with that?

**Comment by jwnorman** [comment]
Hi @nullism,

Embarrassing but funny bug (or feature?!) on my part. The default deck in deck.py is a normal 4 suits and 13 cards for each suit. But after I got the empirical distribution that you see in the readme, I wanted to be extra explicit in my code so I passed in suits and values to the deck constructor, but I did it backwards:
```
        deck = Deck(suit_labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
                    card_values=[1, 2, 3, 4])
```

So what you're seeing are the results from a deck with 13 suits and 4 cards per suit (where you'd play with 13 piles, and you win a lot more :1st_place_medal:). Oops. If you just use `deck = Deck()` (or switch the lists), you'll get the expected distribution.

I'll fix this later - thanks for finding this!

**Comment by nullism** [comment]
Aha, that worked! Thanks for the info. Cool project, btw. We were just playing this game and determined that the odds of winning must be very low, so I found this project. Thanks for making it!

**Comment by jwnorman** [comment]
Cool, I'm glad you like it! I still need to improve the process of determining which pile to reorganize when there's an empty pile. I don't think it's optimal right now. So realistically, odds are probably slightly better than 141:1. Maybe like 130:1.
